# video_transcriber.py
import sys
import os
import json
import yt_dlp
import whisper
import torch
import io
import http.cookiejar
import tempfile

# 设置编码为UTF-8
sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

# 确保临时文件夹存在
TEMP_DIR = os.path.join(os.path.dirname(__file__), "temp_audio")
os.makedirs(TEMP_DIR, exist_ok=True)

# 定义一个空的进度钩子，以覆盖默认的打印行为
def silent_progress_hook(d):
    pass

def load_bili_cookies():
    """从 bili_config.json 加载B站登录Cookie，生成 Netscape 格式 cookie 文件供 yt-dlp 使用"""
    config_path = os.path.join(os.path.dirname(__file__), 'bili_config.json')
    if not os.path.exists(config_path):
        print("未找到 bili_config.json，将不使用Cookie下载", file=sys.stderr)
        return None
    
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
        
        if not config.get('SESSDATA') or not config.get('bili_jct'):
            print("bili_config.json 中缺少必要的Cookie字段", file=sys.stderr)
            return None
        
        # 创建 Netscape 格式的 cookie 文件
        cookie_file = os.path.join(TEMP_DIR, 'bili_cookies.txt')
        with open(cookie_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by video_transcriber.py\n\n")
            # 格式: domain\tinclude_subdomains\tpath\tsecure\texpiry\tname\tvalue
            expiry = "1999999999"
            cookie_entries = [
                ('SESSDATA', config.get('SESSDATA', '')),
                ('bili_jct', config.get('bili_jct', '')),
                ('DedeUserID', config.get('DedeUserID', '')),
                ('buvid3', config.get('buvid3', '')),
                ('buvid4', config.get('buvid4', '')),
                ('b_nut', str(config.get('b_nut', ''))),
            ]
            for name, value in cookie_entries:
                if value:
                    f.write(f".bilibili.com\tTRUE\t/\tFALSE\t{expiry}\t{name}\t{value}\n")
        
        print("已加载B站登录Cookie用于下载", file=sys.stderr)
        return cookie_file
    except Exception as e:
        print(f"加载Cookie失败: {e}", file=sys.stderr)
        return None

def download_audio(bvid):
    video_url = f"https://www.bilibili.com/video/{bvid}"
    output_path = os.path.join(TEMP_DIR, f"{bvid}.%(ext)s")

    # B站特定的headers（使用更新的Chrome UA）
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
        'Referer': 'https://www.bilibili.com/',
    }

    ydl_opts = {
        'format': 'bestaudio[ext=m4a]/bestaudio/best',
        'outtmpl': output_path,
        'quiet': True,
        'no_warnings': True,
        'http_headers': headers,
        'socket_timeout': 30,
        'retries': 3,
        'logger': None,
        'logtostderr': False,
        'progress_hooks': [silent_progress_hook], # 强制使用静默钩子
    }

    # 加载B站登录Cookie以绕过412风控
    cookie_file = load_bili_cookies()
    if cookie_file:
        ydl_opts['cookiefile'] = cookie_file

    try:
        print(f"开始下载视频音频: {video_url}", file=sys.stderr)

        # --- 捕获并重定向 stdout ---
        original_stdout = sys.stdout
        sys.stdout = captured_stdout = io.StringIO()

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(video_url, download=True)
        finally:
            # 无论成功失败，都必须恢复 stdout，否则后续 print 输出会丢失
            sys.stdout = original_stdout
        
        # (可选) 打印被捕获的输出到 stderr 以供调试
        captured_output = captured_stdout.getvalue()
        if captured_output:
            print(f"被捕获的yt-dlp输出:\n{captured_output}", file=sys.stderr)

        print(f"视频信息提取成功: {info.get('title', 'Unknown')}", file=sys.stderr)

        # 查找下载的文件
        for file in os.listdir(TEMP_DIR):
            if file.startswith(bvid + '.'):
                file_path = os.path.join(TEMP_DIR, file)
                print(f"找到下载的文件: {file_path}", file=sys.stderr)
                return file_path
        
        print(f"未找到下载的文件", file=sys.stderr)
        return None
    except Exception as e:
        print(f"下载音频时出错: {str(e)}", file=sys.stderr)
        return None

def transcribe_audio(file_path, model_size="medium", max_duration=None):
    if not file_path:
        return "Audio download failed."

    try:
        # 检查文件大小和时长
        file_size = os.path.getsize(file_path) / (1024 * 1024)  # MB
        print(f"音频文件大小: {file_size:.2f}MB", file=sys.stderr)

        # 如果文件太大，使用更快的模型
        if file_size > 50:  # 大于50MB
            if model_size == "large":
                model_size = "medium"
                print("文件较大，自动切换到medium模型以提高速度", file=sys.stderr)

        device = "cuda" if torch.cuda.is_available() else "cpu"
        if device == "cuda":
            print("使用GPU进行转录加速", file=sys.stderr)
        else:
            print("使用CPU进行转录", file=sys.stderr)

        # 加载模型
        print(f"加载Whisper模型: {model_size}", file=sys.stderr)
        model = whisper.load_model(model_size, device=device)

        # 转录参数优化
        transcribe_options = {
            "language": "zh",
            "task": "transcribe",
            "fp16": torch.cuda.is_available() and device == "cuda",
            "verbose": False,  # 减少输出
        }

        print("开始转录音频...", file=sys.stderr)
        
        # --- 正确处理 max_duration ---
        # 1. 加载音频
        audio = whisper.load_audio(file_path)
        
        # 2. 如果需要，进行切片
        if max_duration:
            print(f"只转录前 {max_duration} 秒的音频。", file=sys.stderr)
            sample_rate = 16000  # whisper 使用 16kHz 采样率
            num_samples = int(max_duration * sample_rate)
            audio = audio[:num_samples]

        # 3. 转录处理后的音频数据
        result = model.transcribe(audio, **transcribe_options)

        transcript = result['text'].strip()
        print(f"转录完成，转录文本长度: {len(transcript)} 字符", file=sys.stderr)

        return transcript

    except Exception as e:
        print(f"转录音频时出错: {str(e)}", file=sys.stderr)
        return "Transcription failed."
    finally:
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                print("临时音频文件已清理", file=sys.stderr)
            except OSError as e:
                print(f"清理临时文件失败: {e}", file=sys.stderr)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(json.dumps({"error": "No BVID provided."}))
        sys.exit(1)

    bvid_input = sys.argv[1]
    model_size = sys.argv[2] if len(sys.argv) > 2 else "medium"
    max_duration = int(sys.argv[3]) if len(sys.argv) > 3 else None

    print(f"转录参数: BV号={bvid_input}, 模型={model_size}, 最大时长={max_duration}", file=sys.stderr)

    audio_file = download_audio(bvid_input)

    if audio_file:
        transcript_text = transcribe_audio(audio_file, model_size, max_duration)
        if "failed" in transcript_text.lower():
             result_json = json.dumps({"error": transcript_text}, ensure_ascii=False)
             print(result_json, flush=True)
        else:
             result_json = json.dumps({"transcript": transcript_text}, ensure_ascii=False)
             print(result_json, flush=True)
    else:
        error_msg = f"Failed to download audio for BVID: {bvid_input}"
        result_json = json.dumps({"error": error_msg}, ensure_ascii=False)
        print(result_json, flush=True)
